services:
  tech-kg-prototype:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-kg-api-dev-prototype:latest
    container_name: tech-kg-api-dev-prototype
    ports:
      - "8080:80"
    restart: unless-stopped
