from db_model.base import Base
from db_model.industry_chain import (
    DwdIndustryChainInfo,
    DwdIndustryChainNewsInfo,
    DwdOrgIndustryChainDtl,
    DwdOrgIndustryChainProdDtl,
)
from db_model.organization import (
    DwdForgActControInfo,
    DwdForgBaseInfo,
    DwdForgBeneficiaryInfo,
    DwdForgExecutiveInfo,
    DwdForgProductInfo,
    DwdForgShareholderInfo,
    DwdForgStockFinInfo,
    DwdForgSubsidiaryInfo,
    DwdOrgAnnualFinancialInfo,
    DwdOrgBidInfo,
    DwdOrgChangerecordInfo,
    DwdOrgExecutiveInfo,
    DwdOrgFinancingInfo,
    DwdOrgHelsInfo,
    DwdOrgImportantNewsInfo,
    DwdOrgInvestInfo,
    DwdOrgMergerAcquisitionInfo,
    DwdOrgOrgProductInfo,
    DwdOrgRecruitInfo,
    DwdOrgRegInfo,
    DwdOrgShareholderInfo,
    DwdOrgStockBase,
    DwdOrgStockFinanceInfo,
    DwdOrgTagInfo,
)
from db_model.paper import (
    DwdEnJournal,
    DwdEnPaper,
    DwdEnPaperAbstract,
    DwdEnPaperAuthor,
    DwdEnPaperCitation,
    DwdEnPaperClassification,
    DwdEnPaperFunding,
    DwdEnPaperReference,
    DwdEnPaperRelated,
    DwdEnPaperTitle,
    DwdZhJournal,
    DwdZhPaper,
    DwdZhPaperAbstract,
    DwdZhPaperAuthor,
    DwdZhPaperCitation,
    DwdZhPaperClassification,
    DwdZhPaperReference,
    DwdZhPaperRelated,
    DwdZhPaperTitle,
)
from db_model.patent import (
    DwdPatent,
    DwdPatentAbstract,
    DwdPatentFamily,
    DwdPatentLegal,
    DwdPatentTitle,
)
from db_model.project import (
    DwdEnProject,
    DwdEnProjectOutput,
    DwdZhProject,
    DwdZhProjectOutput,
)
from db_model.scholar import (
    DwdScholar,
    DwdScholarCoauthor,
    DwdScholarPaperRelation,
    DwdScholarPapers,
    DwdScholarResearchDirection,
    DwdScholarTalentFlag,
)

__all__ = [
    "Base",
    # Scholar
    "DwdScholar",
    "DwdScholarTalentFlag",
    "DwdScholarResearchDirection",
    "DwdScholarPaperRelation",
    "DwdScholarPapers",
    "DwdScholarCoauthor",
    # Patent
    "DwdPatent",
    "DwdPatentTitle",
    "DwdPatentAbstract",
    "DwdPatentLegal",
    "DwdPatentFamily",
    # Chinese Paper
    "DwdZhPaper",
    "DwdZhPaperTitle",
    "DwdZhPaperAbstract",
    "DwdZhPaperAuthor",
    "DwdZhJournal",
    "DwdZhPaperReference",
    "DwdZhPaperCitation",
    "DwdZhPaperClassification",
    "DwdZhPaperRelated",
    # English Paper
    "DwdEnPaper",
    "DwdEnPaperTitle",
    "DwdEnPaperAbstract",
    "DwdEnPaperAuthor",
    "DwdEnJournal",
    "DwdEnPaperReference",
    "DwdEnPaperCitation",
    "DwdEnPaperFunding",
    "DwdEnPaperClassification",
    "DwdEnPaperRelated",
    # Project
    "DwdZhProject",
    "DwdZhProjectOutput",
    "DwdEnProject",
    "DwdEnProjectOutput",
    # Domestic Organization
    "DwdOrgRegInfo",
    "DwdOrgShareholderInfo",
    "DwdOrgExecutiveInfo",
    "DwdOrgOrgProductInfo",
    "DwdOrgAnnualFinancialInfo",
    "DwdOrgImportantNewsInfo",
    "DwdOrgChangerecordInfo",
    "DwdOrgMergerAcquisitionInfo",
    "DwdOrgFinancingInfo",
    "DwdOrgInvestInfo",
    "DwdOrgBidInfo",
    "DwdOrgRecruitInfo",
    "DwdOrgHelsInfo",
    "DwdOrgTagInfo",
    "DwdOrgStockBase",
    "DwdOrgStockFinanceInfo",
    # Foreign Organization
    "DwdForgBaseInfo",
    "DwdForgShareholderInfo",
    "DwdForgSubsidiaryInfo",
    "DwdForgExecutiveInfo",
    "DwdForgProductInfo",
    "DwdForgBeneficiaryInfo",
    "DwdForgActControInfo",
    "DwdForgStockFinInfo",
    # Industry Chain
    "DwdIndustryChainInfo",
    "DwdOrgIndustryChainDtl",
    "DwdOrgIndustryChainProdDtl",
    "DwdIndustryChainNewsInfo",
]
